In [1]:
import numpy as np

In [169]:
np.random.choice(100, 10, replace=False)

array([68, 55, 16, 21, 15, 12, 57, 20,  3, 18])

In [162]:
#        OR
np.random.choice(11, np.random.choice(9, 1)+3, replace=False)+2

array([ 3,  4,  9, 11,  7, 10])

In [193]:
np.random.choice(9, 1)+3

array([4])

In [174]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[np.array([4,3,2,4])]

array([5, 4, 3, 5])

In [1]:
dic1 = {'a':1, 'b':4}
for i in dic1.values():
    print(i)

1
4


In [2]:
import numpy as np
from collections import Counter
arr = np.array([1,2,2,1,1,2,1,1])
Counter(arr)

Counter({1: 5, 2: 3})

In [3]:
np.ones((4,2))*0.5

array([[0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5],
       [0.5, 0.5]])

In [8]:
{3,4,5} & {4,3,2}

{3, 4}

In [4]:
l = [1,2,3]
[1]*3 + [2]*3 +[3]*3

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [5]:
x1 = [1]*5 + [2]*5 + [3]*5 + [4]*5 + [5]*5
x1

[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5]

In [6]:
import xgboost as xgb