# Compressed Sparse Row(CSR) Matrix

In [2]:
import numpy as np
from scipy.sparse import csr_matrix

csr_matrix((3, 4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [6]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data =np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int32)

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [1]:
import networkx as nx
G = nx.path_graph(4)
G.add_edge(5,6)
graphs = list(nx.connected_component_subgraphs(G))

In [10]:
from collections import defaultdict

li1 = [0,0,1,1,1,1,2,2,2,3,3]
item = list('abcdefghiyz')

dic = defaultdict(list)
for x in zip(li1, item):
    dic[x[0]].append(x[1])
    
for k in dic:
    print(dic[k])

['a', 'b']
['c', 'd', 'e', 'f']
['g', 'h', 'i']
['y', 'z']


In [13]:
for i in item:
    print(str(i))

a
b
c
d
e
f
g
h
i
y
z
