In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Flatten, Dense, Dropout, Activation

In [ ]:
class CustomDense(tf.keras.layers.Layer):
    def __init__(self, num_units, activation="relu"):
        super(CustomDense, self).__init__()

        self.num_units = num_units
        self.activation = Activation(activation)

    def build(self, input_shape):
        ## (32, 784) * (784, 10) + (10)

        self.weight = self.add_weight(shape=[input_shape[-1], self.num_units])
        self.bias = self.add_weight(shape=[self.num_units])

    def call(self, input):
        y = tf.matmul(input, self.weight) + self.bias
        y = self.activation(y)
        return y

if __name__ == "__main__":
    mnist = tf.keras.datasets.mnist

    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train = x_train/255.0
    x_test = x_test/255.0

    model = tf.keras.models.Sequential([
        Flatten(input_shape=(28, 28)),
        CustomDense(128, activation="relu"),
        Dropout(0.3),
        CustomDense(10, activation="softmax")
    ])

    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy",
        metrics=["acc"])
    model.fit(x_train, y_train, epochs=5, batch_size=32)
    model.evaluate(x_test, y_test)

In [2]:
# Importing the library
import tensorflow as tf

# Initializing the input tensor
t1 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]


# Printing the input tensor
print('t1: ', t1)
print('t2: ', t2)

# Calculating result
res = tf.concat([t1, t2], 2)

# Printing the result
print('Result: ', res)


t1:  [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
t2:  [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]
Result:  tf.Tensor(
[[[ 1  2  7  4]
  [ 3  4  8  4]]

 [[ 5  6  2 10]
  [ 7  8 15 11]]], shape=(2, 2, 4), dtype=int32)


In [21]:
# Compute some values using a Tensor
c = tf.constant([[[1.0], [2.0]], [[3.0], [4.0]]])
print(c)
d = tf.constant([[[True], [False]], [[True], [True]]])
print(d)
e = tf.concat([c, d], 2)

print(30*'=')
print(e[:,:,1])

tf.Tensor(
[[[1.]
  [2.]]

 [[3.]
  [4.]]], shape=(2, 2, 1), dtype=float32)
tf.Tensor(
[[[ True]
  [False]]

 [[ True]
  [ True]]], shape=(2, 2, 1), dtype=bool)


InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a float tensor but is a bool tensor [Op:ConcatV2] name: concat

In [15]:
import numpy as np
a = np.array([[1,2],[4,3]])
b = np.array([[4,5],[7,8]])

c = np.dstack([a,b])
c

array([[[1, 4],
        [2, 5]],

       [[4, 7],
        [3, 8]]])